### ISSUE TITLE
param without leading dot cause panic

### ISSUE THREAD

**Issue by nirekin** [ekara-platform/engine#26]
In the descriptor a substitution key without a leading `.` cause a `panic: runtime error: invalid memory address or nil pointer dereference` 

> goroutine 1 [running]:
installer/vendor/github.com/ekara-platform/engine/component.(*context).Environment(0xc42019f540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/installer/vendor/github.com/ekara-platform/engine/component/cmanager.go:186 +0x3f
installer/vendor/github.com/ekara-platform/engine.fdump(0xa6a3c0, 0xc4204e4780, 0xc4204bcae0, 0xc42045ef78, 0x491a83, 0xc420082050)
        /go/src/installer/vendor/github.com/ekara-platform/engine/step_dump.go:16 +0xff
installer/vendor/github.com/ekara-platform/engine.launch(0xd1ea30, 0x1, 0x1, 0xa6a3c0, 0xc4204e4780, 0xc4204bcae0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/installer/vendor/github.com/ekara-platform/engine/process.go:16 +0x453
installer/vendor/github.com/ekara-platform/engine.action.run(0x6, 0x5, 0x9ee097, 0x4, 0xd1ea30, 0x1, 0x1, 0xc420318e10, 0xa6a3c0, 0xc4204e4780, ...)
        /go/src/installer/vendor/github.com/ekara-platform/engine/action.go:91 +0x178
installer/vendor/github.com/ekara-platform/engine.actionManager.Run(0xc420318e10, 0x6, 0xa6a3c0, 0xc4204e4780)
        /go/src/installer/vendor/github.com/ekara-platform/engine/action_manager.go:51 +0x23d
installer/vendor/github.com/ekara-platform/installer.Run(0xc420028015, 0xd, 0xc420082f50, 0xc420318e40, 0xc420026010, 0x23, 0xc420024035, 0x4, 0xc42002604b, 0x32, ...)
        /go/src/installer/vendor/github.com/ekara-platform/installer/installer.go:66 +0x386
main.main()
        /go/src/installer/main.go:24 +0x19f

**Comment by nirekin** [comment]
And error message is now returned to the caller
